[project]
name = "math-lab"
version = "0.1.0"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = ["pytest", "jupyter"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["core*"]

[tool.pylint.messages_control]
disable = [
    "too-few-public-methods",    # not relevant for a math utility library
]

[tool.pylint.format]
max-line-length = 88